steps:
  # test
- name: sonarsource/sonar-scanner-cli:4.5
  id: test
  entrypoint: sh
  args:
  - |
    git config --global init.defaultBranch master
    npm install
    npm run test
    sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.pullrequest.key=$_PR_NUMBER -Dsonar.pullrequest.branch=$BRANCH_NAME -Dsonar.scm.revision=$REVISION_ID
  secretEnv: ['SONAR_TOKEN']
  env:
    - 'PR_NUMBER=$_PR_NUMBER'
    - 'BRANCH_NAME=$BRANCH_NAME'
    - 'REVISION_ID=$REVISION_ID'

#    sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.pullrequest.key=$_PR_NUMBER -Dsonar.pullrequest.branch=$BRANCH_NAME -Dsonar.log.level=TRACE -X
#  secretEnv: ['SONAR_TOKEN']
#  env:
#    - 'PR_NUMBER=$_PR_NUMBER'
#    - 'BRANCH_NAME=$BRANCH_NAME'

availableSecrets:
  secretManager:
  - versionName: projects/17761824387/secrets/SONAR_TOKEN/versions/1
    env: "SONAR_TOKEN"
