steps:
  # test
#- name: gcr.io/cloud-builders/git
#  id: git-unshalllo
#  entrypoint: sh
#  args:
#    - '-c'
#    - |
#      git branch -m master $_HEAD_BRANCH
# TODO sonarにPR numberなどを付与する

- name: node:12-slim
  id: test
  entrypoint: sh
  args:
    - npm install
    - npm run test

- name: sonarsource/sonar-scanner-cli:4.5
  id: test
  entrypoint: sh
  args:
  - '-c'
  - |
    git branch -m master $_HEAD_BRANCH
    sonar-scanner -Dproject.settings=sonar-project.properties
  secretEnv: ['SONAR_TOKEN']

availableSecrets:
  secretManager:
  - versionName: projects/17761824387/secrets/SONAR_TOKEN/versions/1
    env: "SONAR_TOKEN"
