steps:
  # test
- name: gcr.io/cloud-builders/git
  id: git-unshalllo
  entrypoint: sh
  args:
    - '-c'
    - |
      ls
      git branch
      git fetch --unshallow
      git branch
      ls
      git checkout -b fixx origin/fixx
      git branch -D master
      git checkout -b develop origin/develop
      git checkout fixx
      git branch
      ls
      git branch -a
      printenv
  secretEnv: ['SONAR_TOKEN']

substitutions:
  _HEAD_BRANCH: "fixx"
  _BASE_BRANCH: "master"

#- name: sonarsource/sonar-scanner-cli:4.5
#  id: test
#  entrypoint: sh
#  args:
#  - '-c'
#  - |
#    ls
#    git status
#    npm install
#    git branch
#    ls
#    sonar-scanner -Dproject.settings=sonar-project.properties
#  secretEnv: ['SONAR_TOKEN']
#  env:
#    - 'PR_NUMBER=$_PR_NUMBER'
#    - 'BRANCH_NAME=$BRANCH_NAME'
#    - 'REVISION_ID=$REVISION_ID'

#    sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.pullrequest.key=$_PR_NUMBER -Dsonar.pullrequest.branch=$BRANCH_NAME -Dsonar.log.level=TRACE -X
#  secretEnv: ['SONAR_TOKEN']
#  env:
#    - 'PR_NUMBER=$_PR_NUMBER'
#    - 'BRANCH_NAME=$BRANCH_NAME'
#    sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.pullrequest.key=$_PR_NUMBER -Dsonar.pullrequest.branch=$BRANCH_NAME
#    ls .scannerwork/
#    cat .scannerwork/report-task.txt

#      git checkout -b master origin/master

availableSecrets:
  secretManager:
  - versionName: projects/17761824387/secrets/SONAR_TOKEN/versions/1
    env: "SONAR_TOKEN"
