version: 2.1

jobs:
  build:
    docker:
      - image: 'circleci/node:10.16.3'
    steps:
      - checkout
      - run:
          name: install and test
          command: npm install && npm run test
      - sonarcloud/scan
        environment:
          - PR_NUMBER=$_PR_NUMBER
          - BRANCH_NAME=$BRANCH_NAME
#      - sonar-scanner -Dproject.settings=sonar-project.properties -Dsonar.pullrequest.key=$_PR_NUMBER -Dsonar.pullrequest.branch=$BRANCH_NAME -Dsonar.log.level=TRACE -X
#        secretEnv: [ 'SONAR_TOKEN' ]
#        env:
#          - 'PR_NUMBER=$_PR_NUMBER'
#          - 'BRANCH_NAME=$BRANCH_NAME'

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2

workflows:
  main:
    jobs:
      - build:
          context: sonarcloud