jobs:
  test:
    docker:
      - image: 'circleci/node:10.16.3'
    steps:
      - checkout
      - run: echo $CIRCLE_BRANCH
      - run: echo $GITHUB_DEFAULT_BRANCH
      - run: echo $GITHUB_SOCIALTABLES_DEPLOYER_TOKEN
      - run: echo $GITHUB_API_TOKEN
      - run: npm install
      - run: npm run test
      - sonarcloud/scan:
#          cache-version: v0
          github-project-slug: onyanko-pon/sonar_cloud_test
          project-key: onyanko-pon_sonar_cloud_test
          coverage-paths: coverage/lcov.info
orbs:
  sonarcloud: socialtables/sonarcloud@1.1.1
version: 2.1
workflows:
  mesure-coverage:
    jobs:
      - test:
          context: sonarcloud
          filters:
            tags:
              only: /.*/
  version: 2